### ISSUE TITLE
It would be better if you restart working on this project. 

### ISSUE THREAD

**Issue by plasmashadow** [citronneur/node-rdpjs#1]
I am very much excited to see how you are going to implement it.

**Comment by citronneur** [comment]
it's done the project is launching but not finish.

**Comment by usko4** [comment]
![tmp_6009-tweetanatomy_example_960px_4-871457100](https://cloud.githubusercontent.com/assets/13239460/8573887/ce521e4c-258b-11e5-8091-1287e1379911.png)
