### ISSUE TITLE
Certain platforms connect to RDP twice

### ISSUE THREAD

**Issue by untoldone** [citronneur/node-rdpjs#13]
Some system configurations seem to run two RDP connections with the same code -- calling all of the callbacks twice.

Specifically nodejs `0.12.7+` and `4.0+` connecting to Windows Server 2008 R2 from ubuntu 14.04 show this issue.

I did not see the same behavior on Mac, or when connecting to Windows 8 from the same ubuntu machine.

**Comment by citronneur** [comment]
Maybe due to protocol negotiation. If there is fail during nego, a twice connection may happen.
