### ISSUE TITLE
winsock2.h fatal error C1083 Impossibile aprire il file inclusione qos.h No such file or directory bignum.vcxproj

### ISSUE THREAD

**Issue by Giancarlo1974** [citronneur/node-rdpjs#14]
I have Windows 10
node v4.2.0
Microsoft Visual Studio 2013 Express

When try to install module using this command:

npm install node-rdpjs  --msvs_version=2013 --build-from-source

i got this error:

  bignum.cc
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winsock2.h(882): fatal error C1083: Impossibile aprire il file inclu
sione 'qos.h': No such file or directory [D:\mstsc.js\node_modules\bignum\build\bignum.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\pippo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pippo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd D:\mstsc.js\node_modules\bignum
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPACKAGEJSON mstsc.js@0.2.4 license should be a valid SPDX license expression
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\pippo\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "node-rdpjs" "--msvs_version=2013" "--build-from-source"
npm ERR! node v4.2.0
npm ERR! npm  v3.3.5
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.10.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bignum@0.10.2 install script 'node-gyp configure build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\mstsc.js\npm-debug.log

Please, help me

**Comment by citronneur** [comment]
ok in next release the bignum dependancy is over. I will use a pure JS library.

**Comment by citronneur** [comment]
I will close this bug when release 0.2.2 will be out

**Comment by Giancarlo1974** [comment]
How many days?

Il giorno lun 23 nov 2015 21:38 Sylvain Peyrefitte <notifications@github.com>
ha scritto:

**Comment by Giancarlo1974** [comment]
I realized that the real problem lies in node gyp
The core of the problem is that node-gyp is no longer being actively developed

This is the best guide I've found:

https://www.robertkehoe.com/2015/03/fix-node-gyp-rebuild-error-on-windows/

But not, however, resolve the problem
Unfortunately too many modules use node-gyp

**Comment by Giancarlo1974** [comment]
I have fixed all compilation problems

See this guide:
http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64
