### ISSUE TITLE
Cannot find module './build/Release/bignum'

### ISSUE THREAD

**Issue by aeikman** [citronneur/node-rdpjs#4]
New to NodeJS. Please excuse me if this is a simple error. Installed bignum globally and for the project yet still getting the message "Cannot find module './build/Release/bignum'".  Running Atom electron  on Yosemite.

**Comment by citronneur** [comment]
Bignum is dependancy of node-rdpjs. But it need a build phase. Maybe an error during build...

**Comment by citronneur** [comment]
ok in next release the bignum dependancy is over. I will use a pure JS library.
