### ISSUE TITLE
I can not install node-rdpjs

### ISSUE THREAD

**Issue by phong-et** [citronneur/node-rdpjs#5]
I run statement install, it shows out many error : http://prntscr.com/8k8hxb
Can you help me fix step by step each error ? Or show me some reasons !
Normally, others nodejs module I install easily, I never got some above errors 
Thanks so much  !

**Comment by IZIPhAnToMIZI** [comment]
This is because of the bignum dependency, you will need to install python to compile that module.

**Comment by phong-et** [comment]
@IZIPhAnToMIZI  thank you. I also solved some error following : 

I installed Python ( only 2.5 - 3.0 - cause message show out when i install lasted version of python) 
It solved  the error of python 
And it throw a next error about missing msbuild : http://stackoverflow.com/questions/28268630/node-gyp-cannot-find-msbuild-exe ( same with my error) - i solved about this error , but it continue show out a message error following : http://prntscr.com/8swp8y. 
I found the topic talk about my error, maybe it same with my problem : https://github.com/ncb000gt/node.bcrypt.js/issues/94
I install node-rdpjs on Window7 
Currently, I haven't solve them yet ! 
Anyone can help me ! Thank you so much !

**Comment by phong-et** [comment]
@IZIPhAnToMIZI  thank you !
It consist 3 error : 
1. Python missing ( solved ) 
2. msbuild missing : http://stackoverflow.com/questions/28268630/node-gyp-cannot-find-msbuild-exe (solved) 
3 .error following : http://prntscr.com/8swp8y (after done fixing error .2)
I install node-rdpjs on Window7

**Comment by citronneur** [comment]
ok in next release the bignum dependancy is over. I will use a pure JS library.

**Comment by IZIPhAnToMIZI** [comment]
@citronneur Awesome! I was actually going to start this, but I'll let you handle it.

**Comment by phong-et** [comment]
I'm desirable next release of you !!!
Thanks all  ;)

**Comment by Giancarlo1974** [comment]
Hi.
I have fixed the problem on bignum

See this guide:
http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64
